version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/rails
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - app
      - payment-processor
    environment:
      DATABASE_URL: postgres://rinha_backend_2025:development@db:5432
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    command: bash -c "bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - .:/rails
    networks:
      - app
      - payment-processor
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgres://rinha_backend_2025:development@db:5432/rinha_backend_development
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
    depends_on:
      - db
      - redis
      - web
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rinha_backend_2025
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - app

volumes:
  db_data:

networks:
  app:
    driver: bridge
  payment-processor:
    external: true
